=== eclipse-dataspace-dcp/decentralized-claims-protocol/issuance/message/schema/credential-offer-message-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CredentialOfferMessage",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "@type": {
      "type": "string"
    },
    "credentialIssuer": {
      "type": "string"
    },
    "credentials": {
      "type": "array",
      "items": {
        "anyOf": [
          { "type": "string" },
          { "$ref": "#/definitions/CredentialObject" }
        ]
      }
    }
  },
  "required": ["@context", "@type", "credentialIssuer", "credentials"],
  "definitions": {
    "CredentialObject": {
      "$ref": "CredentialObject.json"
    }
  }
}

=== eclipse-dataspace-dcp/decentralized-claims-protocol/issuance/message/example/credential-offer-message.json
{
    "@context": ["https://w3id.org/tractusx-trust/v0.8", "http://example.org/context"],
    "@type": "CredentialOfferMessage",
    "credentialIssuer": "https://issuer.example.org",
    "credentials": [
      {
        "@context": "http://example.org/context",
        "@type": "UniversityDegreeCredential",
        "issuer": "https://issuer.example.org",
        "credentialSubject": {
          "id": "did:example:abcdef123456",
          "degree": {
            "type": "BachelorDegree",
            "name": "Bachelor of Science and Arts"
          }
        }
      }
    ]
  }
